import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState } from 'react'

export default function Home() {
  const [result, setResult] = useState('Your joke/meme will be shown here...')

  function generateJoke(){
    const options = {
      method: 'GET',
      headers: {
        'X-RapidAPI-Key': '67c271ac5cmsh69637339f7e7870p1bf1ddjsne9ada738b323',
        'X-RapidAPI-Host': 'humor-jokes-and-memes.p.rapidapi.com'
      }
    };
    
    fetch('https://humor-jokes-and-memes.p.rapidapi.com/jokes/search?exclude-tags=nsfw&min-rating=7&include-tags=one_liner&number=1&max-length=200', options)
      .then(response => response.json())
      .then(response => setResult(response.jokes[0].joke))
      .catch(err => console.error(err));
  }

  

  function generateMeme(){
    const options = {
      method: 'GET',
      headers: {
        'X-RapidAPI-Key': '67c271ac5cmsh69637339f7e7870p1bf1ddjsne9ada738b323',
        'X-RapidAPI-Host': 'humor-jokes-and-memes.p.rapidapi.com'
      }
    };
    
    fetch('https://humor-jokes-and-memes.p.rapidapi.com/memes/random?keywords=rocket&number=3&media-type=image&keywords-in-image=false&min-rating=4', options)
      .then(response => response.json())
      .then(response => setResult(<Image src={response.url} width="100%" height="100%" layout="responsive"></Image>))
      .catch(err => console.error(err));
    
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Jokes App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Jokes App
        </h1>

        <p className={styles.description}>
          Find the funniest jokes and memes
        </p>

        <div class={styles.actionBtn}>
          <button className={styles.jokeBtn} onClick={generateJoke}> Generate Joke </button>
          <button className={styles.memeBtn} onClick={generateMeme}> Generate Meme </button>
        </div>
        <div className={styles.grid}>
            <span className={styles.card}>
              <p>{result}</p>
            </span>
        </div>
      </main>
    </div>
  )
}
